package vista;

import controlador.CancionController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Cancion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Lucho
 */
public class ListarCancionForm extends javax.swing.JPanel {

    private CancionController cancionController;

    public ListarCancionForm() {
        initComponents();
        cancionController = new CancionController(this);
        cancionController.cargarCancionEnTabla();

        
    }

    public void cargarTabla(ArrayList<Cancion> cancion) {
       DefaultTableModel artista = (DefaultTableModel) jTable2.getModel();
       artista.setRowCount(0); // Limpia la tabla antes de agregar nuevos datos
       
        artista.addColumn("ID");
        artista.addColumn("TITULO");
        artista.addColumn("ARTISTA");
        artista.addColumn("AÑO");
        artista.addColumn("GENERO");
        artista.addColumn("DURACION");
   

        for (Cancion Cancion : Cancion) {
            artista.addRow(new Object[]{cancion.getId(), cancion.getTitulo(), cancion.getArtista(), cancion.getAnio(),cancion.getGenero(), cancion.getDuracion()});
        }
        
        artista.fireTableDataChanged();

        jTable2.setModel(artista);
        jTable2.revalidate();
        jTable2.repaint();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable2 = new javax.swing.JTable();

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(jTable1);

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {},
                                {},
                                {},
                                {},
                                {}
                        },
                        new String [] {

                        }
                ));
                jScrollPane2.setViewportView(jTable2);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable jTable2;
        // End of variables declaration//GEN-END:variables
}
