/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucho
 */
public class MainForm extends JFrame {

    private AgregarCancionForm agregarAutomovilForm;
    private ListarCancionForm listarAutomovilForm;
    private EliminarCancionForm eliminarAutomovilForm;
    private ModificarCancionForm1 modificarAutomovilForm1;

    public MainForm() {
        initComponents();

        agregar.addActionListener((java.awt.event.ActionEvent evt) -> {
            mostrarAgregarAutomovilForm(evt);
        });

        listar.addActionListener((java.awt.event.ActionEvent evt) -> {
            listarActionPerformed(evt);
        });

        eliminar1.addActionListener((java.awt.event.ActionEvent evt) -> {
            eliminarFisicoActionPerformed(evt);
        });

        modificar.addActionListener((java.awt.event.ActionEvent evt) -> {
            modificarActionPerformed(evt);
        });

        //####################################################################
        eliminar2.addActionListener((java.awt.event.ActionEvent evt) -> {
            eliminarLogicoActionPerformed(evt);
        });

    }

    //####################################################################
    private void mostrarAgregarAutomovilForm(java.awt.event.ActionEvent evt) {
        agregarAutomovilForm = new AgregarCancionForm();
        JDialog dialog = new JDialog(this, "Agregar Automovil", true);
        dialog.getContentPane().add(agregarAutomovilForm);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {
        listarAutomovilForm = new ListarCancionForm();
        JDialog dialog = new JDialog(this, "Listado de Automoviles", true);
        dialog.getContentPane().add(listarAutomovilForm);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void eliminarFisicoActionPerformed(java.awt.event.ActionEvent evt) {
        eliminarAutomovilForm = new EliminarCancionForm();
        JDialog dialog = new JDialog(this, "Eliminar Automovil", true);
        dialog.getContentPane().add(eliminarAutomovilForm);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {
        modificarAutomovilForm1 = new ModificarCancionForm1();
        JDialog dialog = new JDialog(this, "modificar Automovil", true);
        dialog.getContentPane().add(modificarAutomovilForm1);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

    }

    //####################################################################
    private void eliminarLogicoActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Lógica para eliminado automóvil");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jMenuBar1 = new javax.swing.JMenuBar();
                menu = new javax.swing.JMenu();
                agregar = new javax.swing.JMenuItem();
                modificar = new javax.swing.JMenuItem();
                eliminar1 = new javax.swing.JMenuItem();
                eliminar2 = new javax.swing.JMenuItem();
                listar = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                menu.setText("CRUD CANCIONES");

                agregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                agregar.setText("Agregar");
                agregar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                agregarActionPerformed(evt);
                        }
                });
                menu.add(agregar);

                modificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                modificar.setText("Modificar");
                menu.add(modificar);

                eliminar1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                eliminar1.setText("Eliminado Fisico");
                menu.add(eliminar1);

                eliminar2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                eliminar2.setText("Eliminado Logico");
                menu.add(eliminar2);

                listar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                listar.setText("Listar");
                menu.add(listar);

                jMenuBar1.add(menu);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 431, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 336, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainForm mainForm = new MainForm();
                // Centrar en el monitor principal:
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                int width = (int) (screenSize.getWidth() * 0.5);
                int height = (int) (screenSize.getHeight() * 0.5);
                mainForm.setSize(width, height);
                mainForm.setLocationRelativeTo(null);
                // Desactivar la capacidad de redimensionar la ventana
                mainForm.setResizable(false);
                mainForm.setVisible(true);

            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenuItem agregar;
        private javax.swing.JMenuItem eliminar1;
        private javax.swing.JMenuItem eliminar2;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuItem listar;
        private javax.swing.JMenu menu;
        private javax.swing.JMenuItem modificar;
        // End of variables declaration//GEN-END:variables
}
